import "./globals.css";

export const metadata = {
  title: "Komunly",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="-bg--blue-dark text-white text-[18px]">
        {children}
      </body>
    </html>
  );
}
